[build]
functions = "./functions"

[[redirects]]
  from = "/year-in-review"
  to = "https://2020-year-in-review.bitsofgood.org"
  status = 301
  force = true

[[plugins]]
   package = "netlify-plugin-scheduled-functions"

[plugins.inputs]
  # Run the debounce-scheduler every 10 minutes
  functions = [{ name = "debounce-scheduler", schedule = "*/10 * * * *" }]

[[redirects]]
  from = "/bootcamp"
  to = "https://www.notion.so/gtbitsofgood/Bootcamp-b1fe164df73e42d3b9c2ab0755e4ca49"
  status = 301
  force = true

[[redirects]]
  from = "/scheduler"
  to = "https://gt-scheduler.org"
  status = 301
  force = true
  
  [[redirects]]
  from = "/blog"
  to = "https://bitsofgood.substack.com/"
  status = 301
  force = true
